#!/usr/bin/env bash
source ../make.in

TEX="build/latex/$NAME-documentation.tex"
TMP="build/latex/tmp.tex"
CONTENT="build/latex/content.tex"
content="build/latex/content.tex"

args=($*)
title="$NAME --- Documentation"
author="$AUTHOR"

echo "" > $CONTENT
for i in $(ls build/man/*.tex); do
    cat $i >> $CONTENT
done

cat tex/template.tex > $TMP
sed -E "s/<title>/$title/g" $TMP > $TEX
cat $TEX > $TMP
sed -E "s/<author>/$author/g" $TMP > $TEX
cat $TEX > $TMP
sed -E "s:<content>:$content:g" $TMP > $TEX

rm $TMP
