#!/usr/bin/env bash

SRCDIR=src
BUILDDIR=build

is_debug () {
    args=($*)
    for i in $args; do
        if [[ $i == "--debug" ]];then
            echo "export DEBUG=1" >> make.in
        fi
    done
    return 0
}

make_dirs () {
    mkdir -p build
}

# Write env vars to make.in
echo "# Autogenerated" > make.in
is_debug $*
make_dirs

echo "export SRCDIR=$SRCDIR" >> make.in
echo "export BUILDDIR=$BUILDDIR" >> make.in
echo "export PREP_DOCUMENT_DIR=./" >> make.in
