#!/usr/bin/env bash

NAME="libname"
SRCDIR=src
PREPDIR=prep
BUILDDIR=build
PREP_DOCUMENT_DIR=./
MANWIDTH=72

is_debug () {
    args=($*)
    for i in $args; do
        if [[ $i == "--debug" ]];then
            echo "export DEBUG=1" >> make.in
        fi
    done
    return 0
}

# Write env vars to make.in
echo "# Autogenerated" > make.in
is_debug $*

echo "export NAME=$NAME" >> make.in
echo "export SRCDIR=$SRCDIR" >> make.in
echo "export PREPDIR=$PREPDIR" >> make.in
echo "export BUILDDIR=$BUILDDIR" >> make.in
echo "export PREP_DOCUMENT_DIR=$PREP_DOCUMENT_DIR" >> make.in
echo "export MANWIDTH=$MANWIDTH" >> make.in
