#!/usr/bin/env bash


export CODE_AUTHOR="M. Skocic"
export CODE_NAME="libname"
export CODE_SRCDIR=src
export CODE_PREPDIR=prep
export CODE_BUILDDIR=build
export CODE_PREP_DOCUMENT_DIR=./
export CODE_MANWIDTH=80
export CODE_VERSION=1.0

export DOC_FNAME=main
export DOC_OUTNAME=$CODE_NAME
export DOC_TEX=pdflatex
export DOC_BIB=biber
export DOC_NCL=makeindex
export DOC_BUILD_DIR=doc/build
export DOC_SRC_DIR=src
export DOC_BIN_DIR=build/pdf
export DOC_HTML_DIR=build/html
export DOC_MK4BUILD=make4ht.mk4
export DOC_MK4CFG=make4ht.cfg
DOC_FORMATS="man txt latex html"

FLAGS_RM="-rf"
FLAGS_MV="-f"

OPTION_DEBUG_PREP=0
OPTION_CLEAN=0
OPTION_VERBOSE=0
OPTION_LATEX_VERBOSE="--interaction=batchmode"
OPTION_MK4_LOGLEVEL=fatal

export DEBUG=$OPTION_DEBUG_PREP

args=($*)
for arg in $args; do
    case $arg in
        "--debug_prep")
            OPTION_DEBUG_PREP=1
            ;;
        "--doc_verbose")
            OPTION_VERBOSE=1
            FLAGS_RM="-rfv"
            FLAGS_MV="-fv"
            ;;
        "--doc_verbose_latex")
            OPTION_LATEX_VERBOSE=""
            ;;
        "--doc_debug_make4ht")
            OPTION_MK4_LOGLEVEL=debug
            ;;
        *)
            ;;
    esac
done

echo "[INFO]: Generating folders."
for format in $DOC_FORMATS; do
    mkdir -p $DOC_BUILD_DIR/$format
done
echo "[INFO]: Folders created."


echo "[INFO]: Generating man pages."
files=$(ls prep/doc/*.prepdoc)
for file in $files; do
    man_name=$(basename -s .prepdoc $file)
    man_section=$(echo $man_name | cut -d "." -f 2)
    man_number=${man_section:0:1}
    
    fp_man=$( echo $file | sed "s/.prepdoc//g")
    fp_man=$( echo $fp_man | sed "s:prep/doc:$DOC_BUILD_DIR/man:g")
    fp_mantxt="$fp_man.txt"
    fp_manhtml="$fp_man.html"
    fp_mantex="$fp_man.tex"
    fp_mantexpdf="$fp_man-pdf.tex"
    fp_manpdf="$fp_man.pdf"
   
    # man
    if [[ $VERBOSE == 1 ]]; then echo "   $file -> $fp_man"; fi
	txt2man -s $man_section -t $man_name -r $NAME -v "Library Functions Manual"  $file > $fp_man
    
    # txt
    if [[ $VERBOSE == 1 ]]; then echo "   $fp_man -> $fp_mantxt"; fi
    man $fp_man > $fp_mantxt
    
    # html 
    if [[ $VERBOSE == 1 ]]; then echo "   $fp_man -> $fp_manhtml"; fi
    man2html -r $fp_man > $fp_manhtml
    
    # tex
    if [[ $VERBOSE == 1 ]]; then echo "   $fp_man -> $fp_mantex";fi
    echo "" > $fp_mantex
    echo "\\begin{Verbatim}[frame=lines,label=$man_name]" >> $fp_mantex
    man -l $fp_man >> $fp_mantex
    echo "\\end{Verbatim}" >> $fp_mantex
    echo "" >> $fp_mantex
    echo "" >> $fp_mantex
    echo "" >> $fp_mantex
    
    # pdf
    if [[ $VERBOSE == 1 ]]; then  echo "   $fp_man -> $fp_mantexpdf";fi
    title="$CODE_NAME $CODE_VERSION --- $man_name"
    
    echo "\\documentclass[11pt, a4paper]{article}" > $fp_mantexpdf
    echo "\\usepackage[margin=2cm]{geometry}" >> $fp_mantexpdf
    echo "\\usepackage[exscale]{ccfonts}" >> $fp_mantexpdf
    echo "\\usepackage{fancyvrb}" >> $fp_mantexpdf

    echo  "\\title{$title}" >> $fp_mantexpdf
    echo "\\author{$DOC_AUTHOR}" >> $fp_mantexpdf
    
    echo "\\begin{document}" >> $fp_mantexpdf
    echo "\\maketitle" >> $fp_mantexpdf
    echo "\\input{$fp_mantex}" >> $fp_mantexpdf
    echo "\\end{document}" >> $fp_mantexpdf
    
    tmp_dir="$DOC_BUILD_DIR/man/build_$man_name"
    mkdir -p $tmp_dir
    $DOC_TEX -synctex=1 -output-directory=$tmp_dir $OPTION_LATEX_VERBOSE $fp_mantexpdf
    mv $FLAGS_MV $tmp_dir/"$man_name-pdf.pdf" $fp_manpdf
    rm $FLAGS_RM $tmp_dir
    rm $FLAGS_RM $fp_mantexpdf
done
echo "[INFO]: Man pages created."

echo "[INFO]: Generating text documentation."
DOC="$DOC_BUILD_DIR/txt/$CODE_NAME.txt"
files=$(ls $DOC_BUILD_DIR/man/*.txt)
    echo "$CODE_NAME - DOCUMENTATION - $CODE_VERSION                              " > $DOC
    echo "" >> $DOC

    for i in $files; do
    echo "------------------------------------------------------------------------" >> $DOC
    cat $i >> $DOC
    echo "------------------------------------------------------------------------" >> $DOC
    echo "" >> $DOC
    echo "" >> $DOC
    done
echo "[INFO]: Text documentation created."


echo "[INFO]: Generating latex documentation."
DOC="$DOC_BUILD_DIR/latex/prep.tex"
files=$(ls $DOC_BUILD_DIR/man/*.tex)
echo "" > $DOC
for file in $files; do
    man_name=$(basename -s .tex $file)
    man_section=$(echo $man_name | cut -d "." -f 2)
    man_number=${man_section:0:1}
    echo "\\section{$man_name\\index{$man_name}}\\label{sec_$man_name}" >> $DOC
    # echo "\\input{$file}" >> $DOC
    echo "\\input{build/man/$(basename $file)}" >> $DOC
    echo "" >> $DOC
done
echo "[INFO]: Latex documentation created."


echo "[INFO]: Exporting ENV variables."
fp=make.in
IFS=$'\n'
echo "# Autogenerated" > $fp
envs="$(printenv | grep ^CODE_)"
for i in $envs; do
    echo "export $i" >> $fp
done
echo "export DESTDIR=$DESTDIR" >> $fp
echo "export PREFIX=$PREFIX" >> $fp

envs="$(printenv | grep ^DOC_)"
for i in $envs; do
    echo "export $i" >> $fp
done
echo "[INFO]: ENV variables exported."


echo "[INFO]: Writing LaTeX variable to $fp"
fp=doc/src/make.in.tex
echo "% Autogenerated" > $fp
echo "\\def\\NAME{$CODE_NAME}" >> $fp
echo "\\def\\VERSION{$CODE_VERSION}" >> $fp
echo "\\def\\AUTHOR{$CODE_AUTHOR}" >> $fp
echo "[INFO]: LaTeX variables written."
