#!/usr/bin/env bash

export MS_NAME=MyLib
export MS_VERSION=1.0
export MS_AUTHOR="M. Skocic"
export MS_SRC_DIR=src
export MS_BUILD_DIR=build
export MS_TEX=pdflatex
export MS_MAKEINFO=makeinfo


envs=$(printenv | grep '^MS_')
IFS=$'\n'
echo "# Autogenerated." > make.in
for i in $envs; do
    echo $i
    echo "export $i" >> make.in
done

echo "% Autogenerated." > $MS_SRC_DIR/make.in.tex
echo "\\def\\NAME{$MS_NAME}" >> $MS_SRC_DIR/make.in.tex
echo "\\def\\AUTHOR{$MS_AUTHOR}" >> $MS_SRC_DIR/make.in.tex
