#!/usr/bin/env bash

texi=$1
tex=$2

echo "% Autogenerated: $date" > $tex

IFS=$'\n'

l1=$(grep -n '\\begin{document}' $texi)
l1=$(echo $l1 | cut -d ':' -f 1)
l2=$(grep -n '\\end{document}' $texi)
l2=$(echo $l2 | cut -d ':' -f 1)

l1=$(($l1 + 1))
l2=$(($l2 - 1))
lines="$l1,$l2 p"

sed -n $lines $texi >> $tex
