#!/usr/bin/env bash

export MYDEBIAN_VERSION=$(tr -d '\r' < VERSION | tr -d '\n')
export MYDEBIAN_NAME="prog"
export MYDEBIAN_SRC_DIR="src"
export MYDEBIAN_BUILD_DIR="build"
export MYDEBIAN_MAN_SEC="1"
export MYDEBIAN_MAN_DIR="man/man$MYDEBIAN_MAN_SEC"
export MYDEBIAN_MAN_NAME=$MYDEBIAN_NAME.$MYDEBIAN_MAN_SEC


envs=$(printenv | grep ^MYDEBIAN)
IFS=$'\n'
echo "# Autogenerated" > make.in
for i in $envs; do
    echo $i
    echo "export $i" >> make.in
done

mkdir -p $MYDEBIAN_BUILD_DIR

