@node First Chapter 
@chapter First Chapter 
A simple minimalistic text in chapter 1. 

@section Formatting 

Text can be @b{bold} @i{italic} @t{fixed} @sc{small caps} @emph{emphasized} @strong{strong}
@iflatex
@latex
\citep{gnu}
@end latex
@end iflatex
@ifinfo
\@cite{GNU TexInfo}
@end ifinfo


@section Mathematics 

The inline formulae are @b{valid} for texi @math{j=j_0 \cdot \left(1-\exp \frac{x}{x_0}\right)} and
@cindex inline
as well as multine. 
@fnindex f(x)
@ifinfo 
@cite{test} 
@end ifinfo
@iflatex
@latex 
\citep{antunes2010} 
@end latex
@end iflatex

@section Figures 
Figures are also supported. The floats are directly compatible with @code{info}
@code{latex}. 
@command{makeinfo} allows to compile to @option{--pdf, --html, --latex}.
Figure (@pxref{fig:caption}) shows that images can be imported.
When the format is @option{info} it looks for a @file{*.txt} file and when the
output is pdf it looks for any compatible format such as @file{*.png,*.pdf}.

ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz

ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz


ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
   

ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
   
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
ksfhksdfskjfskfkshfksfskfjdsfksfsf sfsjhdf sfsjkfh sfjsjzirzej sfjsklfz
   

@float figure,fig:caption
@center @image{./src/figures/image,10cm,,,.txt}
@caption{New caption}
@end float

