\input texinfo
@settitle @value{TITLE}


@copying
Copyright @copyright{} @value{AUTHOR}.
@end copying

@titlepage
@center @image{src/figures/head,5cm,,,.png}
@ifnothtml
@title @value{TITLE}
@subtitle Documentation
@end ifnothtml
@author @value{AUTHOR} --- PhD, Electrochemistry
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@node Top
@top @value{TITLE}


@ifinfo
@image{src/figures/head,,,,.txt}
@end ifinfo


@menu
* First Chapter::    The first chapter is the
                      only chapter in this sample.
* Index::            Complete index.
@end menu


@include src/ch1.texi

@node Index
@unnumbered Index

@printindex cp

@bye
